// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/authservice.proto

package authservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Authservice service

func NewAuthserviceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Authservice service

type AuthserviceService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Authservice_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Authservice_PingPongService, error)
}

type authserviceService struct {
	c    client.Client
	name string
}

func NewAuthserviceService(name string, c client.Client) AuthserviceService {
	return &authserviceService{
		c:    c,
		name: name,
	}
}

func (c *authserviceService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Authservice.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authserviceService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Authservice_StreamService, error) {
	req := c.c.NewRequest(c.name, "Authservice.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &authserviceServiceStream{stream}, nil
}

type Authservice_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type authserviceServiceStream struct {
	stream client.Stream
}

func (x *authserviceServiceStream) Close() error {
	return x.stream.Close()
}

func (x *authserviceServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authserviceServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authserviceServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authserviceServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *authserviceService) PingPong(ctx context.Context, opts ...client.CallOption) (Authservice_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Authservice.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &authserviceServicePingPong{stream}, nil
}

type Authservice_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type authserviceServicePingPong struct {
	stream client.Stream
}

func (x *authserviceServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *authserviceServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *authserviceServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authserviceServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authserviceServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *authserviceServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Authservice service

type AuthserviceHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Authservice_StreamStream) error
	PingPong(context.Context, Authservice_PingPongStream) error
}

func RegisterAuthserviceHandler(s server.Server, hdlr AuthserviceHandler, opts ...server.HandlerOption) error {
	type authservice interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Authservice struct {
		authservice
	}
	h := &authserviceHandler{hdlr}
	return s.Handle(s.NewHandler(&Authservice{h}, opts...))
}

type authserviceHandler struct {
	AuthserviceHandler
}

func (h *authserviceHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.AuthserviceHandler.Call(ctx, in, out)
}

func (h *authserviceHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.AuthserviceHandler.Stream(ctx, m, &authserviceStreamStream{stream})
}

type Authservice_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type authserviceStreamStream struct {
	stream server.Stream
}

func (x *authserviceStreamStream) Close() error {
	return x.stream.Close()
}

func (x *authserviceStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authserviceStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authserviceStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authserviceStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *authserviceHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.AuthserviceHandler.PingPong(ctx, &authservicePingPongStream{stream})
}

type Authservice_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type authservicePingPongStream struct {
	stream server.Stream
}

func (x *authservicePingPongStream) Close() error {
	return x.stream.Close()
}

func (x *authservicePingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authservicePingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authservicePingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authservicePingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *authservicePingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
